/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => EmbedMediaPlugin
});
module.exports = __toCommonJS(main_exports);

// src/functions.ts
var import_obsidian2 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  port: 5555,
  baselink: "http://127.0.0.1",
  showInMenuItem: true
};
var MyPluginSettingsTab = class extends import_obsidian.PluginSettingTab {
  constructor(plugin) {
    super(plugin.app, plugin);
    this.plugin = plugin;
  }
  addHeading(heading) {
    return new import_obsidian.Setting(this.containerEl).setName(heading).setHeading();
  }
  addTextSetting(settingName) {
    return new import_obsidian.Setting(this.containerEl).addText((text) => {
      text.setValue(this.plugin.settings[settingName]).setPlaceholder(DEFAULT_SETTINGS[settingName]).onChange(async (value) => {
        this.plugin.settings[settingName] = value;
        await this.plugin.saveSettings();
      });
    });
  }
  addNumberSetting(settingName) {
    return new import_obsidian.Setting(this.containerEl).addText((text) => {
      text.setValue("" + this.plugin.settings[settingName]).setPlaceholder("" + DEFAULT_SETTINGS[settingName]).then((text2) => text2.inputEl.type = "number").onChange(async (value) => {
        this.plugin.settings[settingName] = value === "" ? DEFAULT_SETTINGS[settingName] : +value;
        await this.plugin.saveSettings();
      });
    });
  }
  addToggleSetting(settingName, extraOnChange) {
    return new import_obsidian.Setting(this.containerEl).addToggle((toggle) => {
      toggle.setValue(this.plugin.settings[settingName]).onChange(async (value) => {
        this.plugin.settings[settingName] = value;
        await this.plugin.saveSettings();
        extraOnChange == null ? void 0 : extraOnChange(value);
      });
    });
  }
  addDropdowenSetting(settingName, options, display, extraOnChange) {
    return new import_obsidian.Setting(this.containerEl).addDropdown((dropdown) => {
      var _a;
      const displayNames = /* @__PURE__ */ new Set();
      for (const option of options) {
        const displayName = (_a = display == null ? void 0 : display(option)) != null ? _a : option;
        if (!displayNames.has(displayName)) {
          dropdown.addOption(option, displayName);
          displayNames.add(displayName);
        }
      }
      dropdown.setValue(this.plugin.settings[settingName]).onChange(async (value) => {
        this.plugin.settings[settingName] = value;
        await this.plugin.saveSettings();
        extraOnChange == null ? void 0 : extraOnChange(value);
      });
    });
  }
  addSliderSetting(settingName, min, max, step) {
    return new import_obsidian.Setting(this.containerEl).addSlider((slider) => {
      slider.setLimits(min, max, step).setValue(this.plugin.settings[settingName]).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings[settingName] = value;
        await this.plugin.saveSettings();
      });
    });
  }
  display() {
    this.containerEl.empty();
    this.addNumberSetting("port").setName(
      "Port (for the server to run on)"
    );
    this.addTextSetting("baselink").setName(
      "Base Link (used in replacement only)"
    );
    this.addToggleSetting("showInMenuItem").setName("Show in Menu Item");
  }
};

// src/functions.ts
function embedMediaAsCodeBlock(editor) {
  try {
    let filePath = editor.getSelection();
    if (!filePath) {
      new import_obsidian2.Notice("File path not provided");
      return;
    }
    filePath = filePath.replace("file:///", "");
    let embedType = determineEmbedType(filePath);
    let codeBlock = `\`\`\`media
path: ${filePath}
type: ${embedType}
`;
    if (embedType === "video" || embedType === "iframe") {
      codeBlock += `width: ${640}
height: ${360}
`;
    }
    codeBlock += `\`\`\``;
    editor.replaceSelection(codeBlock);
  } catch (error) {
    console.log("Error:", error);
  }
}
function onEditorMenu(menu, editor, showInMenuItem = true) {
  if (!showInMenuItem)
    return;
  try {
    menu.addItem((item) => {
      item.setTitle("Embed selected media path").setIcon("link").onClick(async () => {
        if (!editor)
          return;
        embedMediaAsCodeBlock(editor);
      });
    });
  } catch (error) {
    console.log("Error :", error);
  }
  return;
}
function generateMediaView(mediainfo, settings = DEFAULT_SETTINGS) {
  var _a, _b;
  try {
    let filePath = mediainfo.path;
    const port = settings.port || DEFAULT_SETTINGS.port;
    const baselink = settings.baselink || DEFAULT_SETTINGS.baselink;
    if (!filePath) {
      new import_obsidian2.Notice("File path not provided");
      return "";
    }
    if (filePath.startsWith("file:///"))
      filePath = filePath.replace("file:///", "");
    filePath = decodeURIComponent(filePath);
    if (!isValidPath(filePath)) {
      new import_obsidian2.Notice("The provided file path or link is not valid.");
      return "";
    }
    let url;
    if (filePath.match(/^https?:\/\//)) {
      url = filePath;
    } else {
      const encodedPath = encodeURIComponent(filePath);
      url = `${baselink}:${port}/?q=${encodedPath}`;
    }
    let embedType = mediainfo.type || determineEmbedType(filePath);
    const width = (_a = mediainfo.width) != null ? _a : 640;
    const height = (_b = mediainfo.height) != null ? _b : 360;
    if (embedType === "video") {
      return `<video width="${width}" height="${height}" controls>
    <source src="${url}" type="video/mp4">
    Your browser does not support the video tag.
</video>`;
    } else if (embedType === "audio") {
      return `<audio controls>
    <source src="${url}" type="audio/mpeg">
    Your browser does not support the audio tag.
</audio>`;
    } else {
      return `<iframe src="${url}" width="${width}" height="${height}" frameborder="0" allowfullscreen></iframe>`;
    }
  } catch (error) {
    console.log("Error:", error);
    return "";
  }
}
function isValidPath(filePath) {
  const isWindowsPath = filePath.match(/^[A-Za-z]:(\\|\/)/) !== null;
  const isUnixPath = filePath.match(/^\//) !== null;
  const isLink = filePath.match(/^https?:\/\//) !== null;
  return isWindowsPath || isUnixPath || isLink;
}
function determineEmbedType(filePath) {
  filePath = filePath.replace("file:///", "");
  if (filePath.match(/\.(mp4|webm|ogg)$/)) {
    return "video";
  } else if (filePath.match(/\.(mp3|wav|ogg)$/)) {
    return "audio";
  } else {
    return "iframe";
  }
}

// src/embedMedia_old.ts
var import_obsidian3 = require("obsidian");
function embedMediOld(input, settings = DEFAULT_SETTINGS, embedType) {
  try {
    let filePath;
    if (typeof input === "string") {
      filePath = input;
    } else {
      filePath = input.getSelection();
    }
    const port = settings.port || DEFAULT_SETTINGS.port;
    const baselink = settings.baselink || DEFAULT_SETTINGS.baselink;
    if (!filePath) {
      new import_obsidian3.Notice("File path not provided");
      return;
    }
    filePath = decodeURIComponent(filePath);
    if (filePath.startsWith("file:///")) {
      filePath = filePath.replace("file:///", "");
    }
    const isWindowsPath = filePath.match(/^[A-Za-z]:(\\|\/)/);
    const isUnixPath = filePath.match(/^\//);
    const isLink = filePath.match(/^https?:\/\//);
    let url;
    if (isLink) {
      url = filePath;
    } else if (isWindowsPath || isUnixPath) {
      const encodedPath = encodeURIComponent(filePath);
      url = `${baselink}:${port}/?q=${encodedPath}`;
    } else {
      new import_obsidian3.Notice("The provided file path or link is not valid.");
      return;
    }
    let embedCode;
    if (embedType === "auto") {
      if (filePath.match(/\.(mp4|webm|ogg)$/)) {
        embedType = "video";
      } else if (filePath.match(/\.(mp3|wav|ogg)$/)) {
        embedType = "audio";
      } else {
        embedType = "iframe";
      }
    }
    if (embedType === "video") {
      embedCode = `<video width="640" height="360" controls>
    <source src="${url}" type="video/mp4">
    Your browser does not support the video tag.
</video>`;
    } else if (embedType === "audio") {
      embedCode = `<audio controls>
    <source src="${url}" type="audio/mpeg">
    Your browser does not support the audio tag.
</audio>`;
    } else {
      embedCode = `<iframe src="${url}" width="640" height="360" frameborder="0" allowfullscreen></iframe>`;
    }
    if (typeof input === "string") {
      return embedCode;
    } else {
      input.replaceSelection(embedCode);
    }
  } catch (error) {
    console.log("Error :", error);
  }
}

// src/main.ts
var import_obsidian5 = require("obsidian");

// src/server.ts
var http = __toESM(require("http"));
var fs = __toESM(require("fs"));
var MediaServer = class {
  constructor(port) {
    this.server = null;
    this.port = port;
  }
  startServer() {
    this.server = http.createServer((req, res) => {
      var _a;
      const urlParams = new URLSearchParams(((_a = req.url) == null ? void 0 : _a.split("?")[1]) || "");
      const filePath = urlParams.get("q");
      if (!filePath) {
        res.writeHead(400, { "Content-Type": "text/plain" });
        res.end("File path not specified");
        return;
      }
      const fullPath = filePath;
      if (!fs.existsSync(fullPath)) {
        res.writeHead(404, { "Content-Type": "text/plain" });
        res.end("File not found");
        return;
      }
      const stat = fs.statSync(fullPath);
      const fileSize = stat.size;
      const ext = (fullPath.split(".").pop() || "mp4").toLowerCase();
      const supportedTypes = {
        png: "image/png",
        gif: "image/gif",
        jpg: "image/jpeg",
        jpeg: "image/jpeg",
        mp4: "video/mp4",
        webm: "video/webm",
        ogg: "video/ogg",
        // ogg: 'audio/ogg',
        ogv: "video/ogg",
        oga: "audio/ogg",
        mp3: "audio/mpeg",
        wav: "audio/wav",
        weba: "audio/webm"
      };
      const head = {
        "Content-Length": fileSize,
        "Content-Type": supportedTypes[ext] || "plain/text"
      };
      res.writeHead(200, head);
      fs.createReadStream(fullPath).pipe(res);
    });
    this.server.listen(this.port, "0.0.0.0", () => {
    });
  }
  stopServer() {
    if (this.server) {
      this.server.close();
      this.server = null;
    }
  }
};

// src/media_blockproccessor.ts
var import_obsidian4 = require("obsidian");
var MediaBlockProcessor = class {
  constructor(app, settings) {
    this.app = app;
    this.settings = settings;
  }
  async run(source, el) {
    try {
      const data = this.parseMediaInfo(source);
      const type = data.type ? data.type : "auto";
      el.innerHTML = generateMediaView(data, this.settings);
    } catch (error) {
      el.createEl("p", { text: `Error parsing YAML: ${error.message}` });
    }
  }
  parseMediaInfo(source) {
    const parsed = (0, import_obsidian4.parseYaml)(source);
    if (!parsed.path || parsed.path.length < 3) {
      throw new Error("Invalid path provided.");
    }
    return {
      path: parsed.path,
      type: parsed.type,
      width: parsed.width,
      height: parsed.height
    };
  }
};

// src/main.ts
var EmbedMediaPlugin = class extends import_obsidian5.Plugin {
  constructor() {
    super(...arguments);
    this.serverRunning = false;
    this.updateStatusElement = () => {
      const statusText = this.serverRunning ? "\u{1F7E2}" : "\u{1F534}";
      const statusElement = document.querySelector(
        "#local-media-server-status"
      );
      if (this.statusElement && statusElement) {
        statusElement.textContent = statusText;
      } else {
        this.statusElement.createEl("span", {
          text: statusText,
          attr: {
            id: "local-media-server-status"
          }
        });
      }
    };
    this.toggleServer = () => {
      if (!this.serverRunning) {
        try {
          this.server.startServer();
          this.serverRunning = true;
        } catch (error) {
          new import_obsidian5.Notice(`Failed to start server: ${error.message}`);
          this.serverRunning = false;
        }
        new import_obsidian5.Notice(
          `Local Media server started on port ${this.settings.port}`
        );
      } else {
        this.serverRunning = false;
        this.server.stopServer();
        new import_obsidian5.Notice("Local Media server stopped");
      }
      this.updateStatusElement();
      this.updateRibbonIconColor();
    };
  }
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new MyPluginSettingsTab(this));
    this.server = new MediaServer(this.settings.port);
    try {
      this.server.startServer();
      this.serverRunning = true;
    } catch (error) {
      new import_obsidian5.Notice(`Failed to start server: ${error.message}`);
      this.serverRunning = false;
    }
    this.toggleRibbon = this.addRibbonIcon(
      "server-crash",
      "Toggle media server",
      this.toggleServer
    );
    this.addCommand({
      id: "embed-in-iframe-0",
      name: "Embed in iframe tag",
      editorCallback(editor, ctx) {
        embedMediOld(editor, this.settings, "iframe");
      }
    });
    this.addCommand({
      id: "embed-in-videotag-LocalMedia",
      name: "Embed in video tag",
      editorCallback(editor, ctx) {
        embedMediOld(editor, this.settings, "video");
      }
    });
    this.addCommand({
      id: "embed-in-audiotag-LocalMedia",
      name: "Embed in audio tag",
      editorCallback(editor, ctx) {
        embedMediOld(editor, this.settings, "audio");
      }
    });
    this.addCommand({
      id: "toggleserver-LocalMedia",
      name: "Toggle local media server",
      callback: () => {
        this.toggleServer();
      }
    });
    this.addCommand({
      id: "embed-in-auto-localMedia",
      name: "Embed auto",
      editorCallback(editor, ctx) {
        embedMediOld(editor, this.settings, "auto");
      }
    });
    this.addCommand({
      id: "embed-in-codeblock-localMedia",
      name: "Embed as code block",
      editorCallback(editor, ctx) {
        embedMediaAsCodeBlock(editor);
      }
    });
    this.registerEvent(
      this.app.workspace.on(
        "editor-menu",
        (menu, editor) => {
          onEditorMenu(menu, editor, this.settings.showInMenuItem);
        }
      )
    );
    this.statusElement = this.addStatusBarItem();
    this.updateStatusElement();
    this.updateRibbonIconColor();
    this.statusElement.addEventListener("click", () => {
      this.toggleServer();
    });
    this.registerMarkdownCodeBlockProcessor("media", (source, el, ctx) => {
      const obj = new MediaBlockProcessor(this.app, this.settings);
      obj.run(source, el);
    });
  }
  async loadSettings() {
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      await this.loadData()
    );
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async unload() {
    this.server.stopServer();
    await this.saveSettings();
    this.statusElement.remove();
  }
  updateRibbonIconColor() {
    this.toggleRibbon.style.color = this.serverRunning ? "rgb(36, 233, 36)" : "";
  }
};

/* nosourcemap */